### PR TITLE
[fix]: resolve pointer misalignment in multiple inheritance

### LINKED ISSUE #220: [BUG] Incorrect message routing/logic hijacking due to pointer misalignment in multiple inheritance
### Description
The `ex_actor` framework suffers from a type-erasure bug related to C++ multiple inheritance memory layout. When an actor implementation inherits from multiple interfaces, the framework's current message dispatching logic fails to perform the necessary **pointer adjustment** when casting from `void*`.
https://github.com/ex-actor/ex-actor/blob/db959614b5a33d757daca8df245ec355c5cc6193/include/ex_actor/internal/actor.h#L285

### Core Cause: `void*` vs. Multiple Inheritance "Parallax"
In C++, interfaces in a multiple-inheritance class are laid out sequentially in memory. If a class `Derived` inherits from `BaseA` and `BaseB`, the `BaseB` subobject is typically located at a non-zero offset from the start of `Derived`.

The framework stores actor instances as `void*` pointing to the physical start of the object (0-byte offset). When calling a method on `BaseB`, it performs:
```cpp
void* instance = actor->get_raw_ptr(); // Points to 0-byte (BaseA position)
BaseB* target = static_cast<BaseB*>(instance); // BUG! 
```
Since the source is `void*`, `static_cast` performs a bitwise copy rather than a pointer adjustment. As a result, `target` incorrectly points to the `BaseA` subobject. If `BaseA` and `BaseB` have virtual functions at the same vtable index, the CPU will execute the function from `BaseA` instead of `BaseB`.

### Reproduction
```cpp
struct BaseA {
    virtual int GetA() { return 1; }
};

struct BaseB {
    virtual int GetB() { return 2; }
};

struct Derived : public BaseA, public BaseB {
    int GetA() override { return 10; }
    int GetB() override { return 20; }
};

TEST(BugTest, MultipleInheritanceRepro) {
    auto actor = co_await ex_actor::Spawn<Derived>();
    
    // Correctly returns 10 because BaseA is the first base
    int a = co_await actor.Send<&BaseA::GetA>(); 
    
    // FAILS: Returns 10 (BaseA::GetA) instead of 20 (BaseB::GetB)
    int b = co_await actor.Send<&BaseB::GetB>(); 
    EXPECT_EQ(b, 20); 
}
```

### Proposed Fix
The fix involves ensuring that throughout the `ActorRef<T>` lifecycle, we maintain a correctly typed and adjusted pointer. 
1. Add a typed `UserClass* instance_ptr_` to `LocalActorRef<UserClass>`.
2. Leverage C++ implicit pointer adjustment during `ActorRef` polymorphic conversions (e.g., `ActorRef<Derived>` to `ActorRef<BaseB>`).
3. Pass the adjusted `instance_ptr_` to `CallActorMethodUseTuple` instead of relying on the type-erased `void*` inside `TypeErasedActor`.

Proposed Logic (Fixed)

```
template <class UserClass>
class ActorRef {
    TypeErasedActor* actor;
    UserClass* adjusted_ptr; // Store the correctly offset pointer
    // Leverage C++ implicit conversion to handle offsets automatically
    template <class Other>
    ActorRef(const ActorRef<Other>& other) {
        this->actor = other.actor;
        // The compiler inserts the correct byte offset here!
        this->adjusted_ptr = static_cast<UserClass*>(other.adjusted_ptr);
    }
    void Send() {
        // Pass the perfectly aligned pointer to the dispatch logic
        actor->CallActorMethod(this->adjusted_ptr, ...);
    }
};
```

if there are nothing wrong i'll fix it

### PR DESCRIPTION
**Pull request by SYSUljz**
- Refactor `CallActorMethodUseTuple` enabling `void*` -> `ActualClass*` -> `Base*`
 - Enhanced `BasicActorRef` to store a pre-adjusted `instance_ptr_`.
 - Updated `remote_handler_registry.h` to capture and pass the real actor  type (derived from the factory function) to the dispatch logic
 - Added object slicing detection in the `Actor` constructor to warn users
 - create `multiple_inheritance_test.cc`

Fixes #220

### CODE REVIEW

File: include/ex_actor/internal/actor.h [hunk 1]
```diff
@@ -270,19 +279,25 @@ class Actor : public TypeErasedActor {
 
 template <auto kMethod, class... Args>
 ex::sender auto TypeErasedActor::CallActorMethod(Args... args) {
-  return CallActorMethodUseTuple<kMethod>(std::make_tuple(std::move(args)...));
+  return CallActorMethodUseTuple<kMethod>(nullptr, std::make_tuple(std::move(args)...));
 }
```
[the remark this answers is not in the document]
Comment (SYSUljz) [reply include/ex_actor/internal/actor.h]: In remote mode i can get ActualClass in remote_handler_registry

File: include/ex_actor/internal/actor.h [hunk 2]
```diff
@@ -45,8 +45,8 @@ class TypeErasedActor {
   template <auto kMethod, class... Args>
   ex::sender auto CallActorMethod(Args... args);
 
-  template <auto kMethod, class... Args>
-  ex::sender auto CallActorMethodUseTuple(std::tuple<Args...> args_tuple);
+  template <auto kMethod, class ActualClass = typename Signature<decltype(kMethod)>::ClassType, class... Args>
```
[the remark this answers is not in the document]
Comment (SYSUljz) [reply include/ex_actor/internal/actor.h]: In remote mode i can get ActualClass in remote_handler_registry

File: include/ex_actor/internal/basic_actor_ref.h [hunk 3]
```diff
@@ -69,16 +78,22 @@ class BasicActorRef {
...
 
   bool IsEmpty() const { return is_empty_; }
   uint64_t GetActorId() const { return actor_id_; }
 
  protected:
-  bool is_empty_;
+  bool is_empty_ = true;
   uint64_t actor_id_ = 0;
   TypeErasedActor* type_erased_actor_ = nullptr;
+  void* instance_ptr_ = nullptr;
```
Comment (lixin-wei) [inline include/ex_actor/internal/basic_actor_ref.h]: `adjusted_ptr_` sounds better, `instance_ptr_` sounds like it points to the root address.

also, can we store `UserClass*` here dicrectly? no need to be a `void*`

File: include/ex_actor/internal/basic_actor_ref.h [hunk 4]
```diff
@@ -49,13 +52,19 @@ class BasicActorRef {
     requires std::is_convertible_v<Other*, UserClass*>
   // NOLINTNEXTLINE(google-explicit-constructor) - implicit conversion is intentional for polymorphism support
   BasicActorRef(const BasicActorRef<Other>& other)
-      : is_empty_(other.is_empty_), actor_id_(other.actor_id_), type_erased_actor_(other.type_erased_actor_) {}
+      : is_empty_(other.is_empty_),
+        actor_id_(other.actor_id_),
+        type_erased_actor_(other.type_erased_actor_),
+        instance_ptr_(static_cast<UserClass*>(static_cast<Other*>(other.instance_ptr_))) {}
```
Comment (lixin-wei) [inline include/ex_actor/internal/basic_actor_ref.h]: this can be simplified to
```cpp
adjusted_ptr_(static_cast<UserClass*>(other.adjusted_ptr_))
```
if we store `UserClass* adjusted_ptr_` directly.

so as what in `operator=` and `SendLocal`

File: include/ex_actor/internal/actor.h [hunk 5]
```diff
@@ -168,6 +168,15 @@ class Actor : public TypeErasedActor {
       user_class_instance_ = std::make_unique<UserClass>(std::move(args)...);
     }
     cached_user_class_instance_address_ = user_class_instance_.get();
+
+    // Check for object slicing: verify that the actual object type matches UserClass
+    if (typeid(*user_class_instance_) != typeid(UserClass)) {
```
[the remark this answers is not in the document]
Comment (lixin-wei) [reply include/ex_actor/internal/actor.h]: @SYSUljz  In what cases will this check fail?

**Review by lixin-wei — COMMENTED** [review]
Looks great overall, nice job, some comments on code details.

File: include/ex_actor/internal/actor.h [hunk 6]
```diff
@@ -270,19 +279,25 @@ class Actor : public TypeErasedActor {
...
 template <auto kMethod, class... Args>
 ex::sender auto TypeErasedActor::CallActorMethod(Args... args) {
-  return CallActorMethodUseTuple<kMethod>(std::make_tuple(std::move(args)...));
+  return CallActorMethodUseTuple<kMethod>(nullptr, std::make_tuple(std::move(args)...));
 }
 
-template <auto kMethod, class... Args>
-ex::sender auto TypeErasedActor::CallActorMethodUseTuple(std::tuple<Args...> args_tuple) {
+template <auto kMethod, class ActualClass, class... Args>
+ex::sender auto TypeErasedActor::CallActorMethodUseTuple(void* instance_ptr, std::tuple<Args...> args_tuple) {
```
Comment (lixin-wei) [inline include/ex_actor/internal/actor.h]: the method is a bit too arcane, too many args.

We can force it to only accept adjusted ptr:
```cpp
// it seems can be a non-member function now.
template <auto kMethod, class PtrClass, class... Args>
requires(std::is_invocable_v<decltype(kMethod), PtrClass*, Args...>)
ex::sender auto CallActorMethodUseTuple(PtrClass* adjusted_ptr, std::tuple<Args...> args_tuple) {
  // calls the method using adjusted_ptr directly.
}
```

Then in `BasicActorRef::SendLocal`, the second template arg will be correct, which was wrong now, ActualType is not UserClass.

In `remote_handler_registry.h`, do the cast outside `CallActorMethodUseTuple`:

```cpp
ActualClass* actual_class_ptr = static_cast<ActualClass*>(...);
CallActorMethodUseTuple<kMethod, ActualClass>(actual_class_ptr, ...)
```

File: include/ex_actor/internal/actor.h [hunk 7]
```diff
@@ -45,8 +45,8 @@ class TypeErasedActor {
   template <auto kMethod, class... Args>
   ex::sender auto CallActorMethod(Args... args);
```
Comment (lixin-wei) [inline include/ex_actor/internal/actor.h]: `CallActorMethod` seems is not used anywhere now, can be removed

File: include/ex_actor/internal/remote_handler_registry.h [hunk 8]
```diff
@@ -126,6 +126,8 @@ class RemoteFuncHandlerRegistrar {
     using ActorClass = Signature<decltype(kCreateFn)>::ReturnType;
     ActorCreationArgs creation_args =
         DeserializeFnArgs<kCreateFn>(context.serialized_args, context.actor_ref_serde_ctx);
+    // Note: Object slicing detection is performed in Actor<UserClass, kCreateFn>::Actor() constructor
+    // via typeid comparison. If the object type doesn't match UserClass, a warning will be logged.
```
Comment (lixin-wei) [inline include/ex_actor/internal/remote_handler_registry.h]: stale comment, remove it

**Comment by lixin-wei** [comment]
@SYSUljz Merged, thank you for the contribution! It's very impressive that you can dive such deep in the first contribution 👍
